apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-dev.yaml
  - app-staging.yaml
  - app-canary.yaml
  - app-prod.yaml

commonLabels:
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/managed-by: argocd
