apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - hpa.yaml
  - ingress.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - serviceaccount.yaml

commonLabels:
  app: app
  managed-by: kustomize

images:
  - name: ghcr.io/OWNER/REPO
    newName: ghcr.io/OWNER/REPO
    newTag: latest
